-- Antes de hacer el insealbumesrt, comprobar que los usuarios tienen ese id, sino, cambiarlo

insert into pibd.albumes (Titulo, Descripcion, Usuario) values
('Animales', 'Las mejores fotos de animales', 40),
('Paisajes', 'Las fotos más bonitas de paisajes', 40),
('Otros', 'Fotos sin clasificar', 40),
('Animales', 'Las mejores fotos de animales', 41),
('Paisajes', 'Las fotos más bonitas de paisajes', 41),
('Otros', 'Fotos sin clasificar', 41),
('Animales', 'Las mejores fotos de animales', 42),
('Paisajes', 'Las fotos más bonitas de paisajes', 42),
('Otros', 'Fotos sin clasificar', 42),
('Animales', 'Las mejores fotos de animales', 43),
('Paisajes', 'Las fotos más bonitas de paisajes', 43),
('Otros', 'Fotos sin clasificar', 43),
('Animales', 'Las mejores fotos de animales', 44),
('Paisajes', 'Las fotos más bonitas de paisajes', 44),
('Otros', 'Fotos sin clasificar', 44),
('Animales', 'Las mejores fotos de animales', 45),
('Paisajes', 'Las fotos más bonitas de paisajes', 45),
('Otros', 'Fotos sin clasificar', 45),
('Animales', 'Las mejores fotos de animales', 46),
('Paisajes', 'Las fotos más bonitas de paisajes', 46),
('Otros', 'Fotos sin clasificar', 46),
('Animales', 'Las mejores fotos de animales', 47),
('Paisajes', 'Las fotos más bonitas de paisajes', 47),
('Otros', 'Fotos sin clasificar', 47),
('Animales', 'Las mejores fotos de animales', 48),
('Paisajes', 'Las fotos más bonitas de paisajes', 48),
('Otros', 'Fotos sin clasificar', 48),
('Animales', 'Las mejores fotos de animales', 49),
('Paisajes', 'Las fotos más bonitas de paisajes', 49),
('Otros', 'Fotos sin clasificar', 49);