/* AMÉRICA*/
insert into pibd.paises (NomPais, Continente) values
('Antigua y Barbuda', 'América'),
('Argentina', 'América'),
('Bahamas', 'América'),
('Barbados', 'América'),
('Belice', 'América'),
('Bolivia', 'América'),
('Brasil', 'América'),
('Canadá', 'América'),
('Chile', 'América'),
('Colombia', 'América'),
('Costa Rica', 'América'),
('Cuba', 'América'),
('Dominica', 'América'),
('Ecuador', 'América'),
('El Salvador', 'América'),
('Estados Unidos de América', 'América'),
('Granada', 'América'),
('Guatemala', 'América'),
('Guyana', 'América'),
('Haití', 'América'),
('Honduras', 'América'),
('Jamaica', 'América'),
('México', 'América'),
('Nicaragua', 'América'),
('Panamá', 'América'),
('Paraguay', 'América'),
('Perú', 'América'),
('República Dominicana', 'América'),
('San Cristóbal y Nieves', 'América'),
('San Vicente y las Granadinas', 'América'),
('Santa Lucía', 'América'),
('Surinam', 'América'),
('Trinidad y Tobago', 'América'),
('Uruguay', 'América'),
('Venezuela', 'América');


/*EUROPA*/
insert into pibd.paises (NomPais, Continente) values
('Albania', 'Europa'),
('Alemania', 'Europa'),
('Andorra', 'Europa'),
('Austria', 'Europa'),
('Bélgica', 'Europa'),
('Bielorrusia', 'Europa'),
('Bosnia y Herzegovina', 'Europa'),
('Bulgaria', 'Europa'),
('Ciudad del Vaticano', 'Europa'),
('Croacia', 'Europa'),
('Dinamarca', 'Europa'),
('Eslovaquia', 'Europa'),
('Eslovenia', 'Europa'),
('España', 'Europa'),
('Estonia', 'Europa'),
('Finlandia', 'Europa'),
('Francia', 'Europa'),
('Grecia', 'Europa'),
('Hungría', 'Europa'),
('Irlanda', 'Europa'),
('Islandia', 'Europa'),
('Italia', 'Europa'),
('Letonia', 'Europa'),
('Liechtenstein', 'Europa'),
('Lituania', 'Europa'),
('Luxemburgo', 'Europa'),
('Macedonia', 'Europa'),
('Malta', 'Europa'),
('Moldavia', 'Europa'),
('Mónaco', 'Europa'),
('Montenegro', 'Europa'),
('Noruega', 'Europa'),
('Países Bajos', 'Europa'),
('Polonia', 'Europa'),
('Portugal', 'Europa'),
('Reino Unido', 'Europa'),
('Répública Checa', 'Europa'),
('Rumanía', 'Europa'),
('San Marino', 'Europa'),
('Serbia', 'Europa'),
('Suecia', 'Europa'),
('Suiza', 'Europa'),
('Ucrania', 'Europa');

/*ÁFRICA*/
insert into pibd.paises (NomPais, Continente) values
('Angola', 'África'),
('Argelia', 'África'),
('Benín', 'África'),
('Botsuana', 'África'),
('Burkina Faso', 'África'),
('Burundi', 'África'),
('Cabo Verde', 'África'),
('Camerún', 'África'),
('Chad', 'África'),
('Comoras', 'África'),
('Costa de Marfil', 'África'),
('Egipto', 'África'),
('Eritrea', 'África'),
('Etiopía', 'África'),
('Gabón', 'África'),
('Gambia', 'África'),
('Ghana', 'África'),
('Guinea', 'África'),
('Guinea-Bisáu', 'África'),
('Guinea Ecuatorial', 'África'),
('Kenia', 'África'),
('Lesoto', 'África'),
('Liberia', 'África'),
('Libia', 'África'),
('Madagascar', 'África'),
('Malaui', 'África'),
('Malí', 'África'),
('Marruecos', 'África'),
('Mauricio', 'África'),
('Mauritania', 'África'),
('Mozambique', 'África'),
('Namibia', 'África'),
('Níger', 'África'),
('Nigeria', 'África'),
('República Centroafricana', 'África'),
('República del Congo', 'África'),
('Répública Democrática del Congo', 'África'),
('Ruanda', 'África'),
('Santo Tomé y Principe', 'África'),
('Senegal', 'África'),
('Seychelles', 'África'),
('Sierra Leona', 'África'),
('Somalia', 'África'),
('Suazilandia', 'África'),
('Sudáfrica', 'África'),
('Sudán', 'África'),
('Sudán del Sur', 'África'),
('Tanzania', 'África'),
('Togo', 'África'),
('Túnez', 'África'),
('Uganda', 'África'),
('Yibuti', 'África'),
('Zambia', 'África'),
('Zimbabue', 'África');

/*ÁSIA*/
insert into pibd.paises (NomPais, Continente) values
('Afganistán', 'Ásia'),
('Arabia Saudita', 'Ásia'),
('Bangladés', 'Ásia'),
('Baréin', 'Ásia'),
('Birmania (Myanmar)', 'Ásia'),
('Brunéi', 'Ásia'),
('Bután', 'Ásia'),
('Camboya', 'Ásia'),
('Catar', 'Ásia'),
('China', 'Ásia'),
('Corea del Norte', 'Ásia'),
('Corea del Sur', 'Ásia'),
('Emiratos Árabes Unidos', 'Ásia'),
('Filipinas', 'Ásia'),
('India', 'Ásia'),
('Indonesia', 'Ásia'),
('Irak', 'Ásia'),
('Irán', 'Ásia'),
('Israel', 'Ásia'),
('Japón', 'Ásia'),
('Jordania', 'Ásia'),
('Kirguistán', 'Ásia'),
('Kuwait', 'Ásia'),
('Laos', 'Ásia'),
('Líbano', 'Ásia'),
('Malasia', 'Ásia'),
('Maldivas', 'Ásia'),
('Mongolia', 'Ásia'),
('Nepal', 'Ásia'),
('Omán', 'Ásia'),
('Pakistán', 'Ásia'),
('Singapur', 'Ásia'),
('Siria', 'Ásia'),
('Sir Lanka', 'Ásia'),
('Tailandia', 'Ásia'),
('Tayikistán', 'Ásia'),
('Timor Oriental', 'Ásia'),
('Turkmenistán', 'Ásia'),
('Uzbekistán', 'Ásia'),
('Vietnam', 'Ásia'),
('Yemen', 'Ásia');

/*OCEANÍA*/
insert into pibd.paises (NomPais, Continente) values
('Australia', 'Oceanía'),
('Fiyi', 'Oceanía'),
('Islas Marshall', 'Oceanía'),
('Islas Salomón', 'Oceanía'),
('Kiribati', 'Oceanía'),
('Micronesia', 'Oceanía'),
('Nauru', 'Oceanía'),
('Nueva Zelanda', 'Oceanía'),
('Palaos', 'Oceanía'),
('Papúa Nueva Guinea', 'Oceanía'),
('Samoa', 'Oceanía'),
('Tonga', 'Oceanía'),
('Tuvalu', 'Oceanía'),
('Vanuatu', 'Oceanía');

/*EUROASIA*/
insert into pibd.paises (NomPais, Continente) values
('Armenia', 'Euroasia'),
('Azerbaiyán', 'Euroasia'),
('Chipre', 'Euroasia'),
('Georgia', 'Euroasia'),
('Kazajistán', 'Euroasia'),
('Rusia', 'Euroasia'),
('Turquía', 'Euroasia');

