<h2 id="tarifas">Tarifas</h2>
<table>
    <tr>
        <th>Concepto</th>
        <th>Tarifa</th>
    </tr>
    <tr>
        <td>&lt; 5 páginas</td>
        <td>0.10 € por pág.</td>
    </tr>
    <tr>
        <td>entre 5 y 10 páginas</td>
        <td>0.08 € por pág.</td>
    </tr>
    <tr>
        <td>&gt; 11 páginas</td>
        <td>0.07 € por pág.</td>
    </tr>
    <tr>
        <td>Blanco y negro</td>
        <td>0 €</td>
    </tr>
    <tr>
        <td>Color</td>
        <td>0.05 € por foto</td>
    </tr>
    <tr>
        <td>Resolución &gt; 300 dpi</td>
        <td>0.02 € por foto</td>
    </tr>
</table><br>