<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale = 1.0" />
    <meta name="description" content="Sitio web de gestión de álbumes de fotos">
    <meta name="robots" content="noindex, nofollow">
    <link rel="shortcut icon" href="images/Logo2.png"/>
    <link rel="stylesheet" type="text/css" href="css/fontello.css"/>
    <link rel="stylesheet" type="text/css" href="css/estilo.css"/>
    <link rel="stylesheet" type="text/css" href="css/print.css" media="print"/>

    <link rel="alternate stylesheet" type="text/css" href="css/print.css" title="Estilo impresión"/>
    <link rel="alternate stylesheet" type="text/css" href="css/accesible.css" title="Estilo accesible"/>
    <link rel="alternate stylesheet" type="text/css" href="css/adaptativo.css" title="Estilo adaptativo"/>

    <title><?php echo $title; ?></title>
</head>

<body>